### ISSUE TITLE
[建议]你可以增加更多版本的分支吗？Github上只有1.21的代码让我很崩溃

### ISSUE THREAD

**Issue by MulatramAwA** [hotpad100c/scheduledtickvisulizer#3]
如题，本人对高版本没有意见，但是建议您把其他版本的分支增加到Github上，这样方便开发😘
你可以只添加一些你认为重要的版本,例如:
1.21.1;1.20.4;1.20.1;1.19.2
因为其他版本几乎没人玩（

**Comment by hotpad100c** [comment]
其他版本的分支暂时还不存在（）
我需要时间来进行向下支持qaq，主要是1.20.5以下的渲染和发包都不一样，我会i尽快向下支持的:.(
当然，如果有人愿意帮忙的话，我会超级happy

**Comment by MulatramAwA** [comment]
我很乐意在节假日帮忙👍👍，当然平时我也是要上学的😭😭😭
